// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTCdmZ7utVgiF8Bbj-qHSd_hOm2SZTmCo',
    appId: '1:664598213291:web:96a62327607a28bd2f7dee',
    messagingSenderId: '664598213291',
    projectId: 'prodapp-dda61',
    authDomain: 'prodapp-dda61.firebaseapp.com',
    storageBucket: 'prodapp-dda61.firebasestorage.app',
    measurementId: 'G-07YNS5TC6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSmVzfKMzw8OpQzYVWDkVDg4XC0_yHPdQ',
    appId: '1:664598213291:android:f6c7a1e9d95844e52f7dee',
    messagingSenderId: '664598213291',
    projectId: 'prodapp-dda61',
    storageBucket: 'prodapp-dda61.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTCdmZ7utVgiF8Bbj-qHSd_hOm2SZTmCo',
    appId: '1:664598213291:web:3ea2227abc0da3632f7dee',
    messagingSenderId: '664598213291',
    projectId: 'prodapp-dda61',
    authDomain: 'prodapp-dda61.firebaseapp.com',
    storageBucket: 'prodapp-dda61.firebasestorage.app',
    measurementId: 'G-95PX6QJN99',
  );
}
